
services:
  webapp:
    build: .
    ports:
      - "8081:8080"
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: /
        target: /rootfs
        read_only: true
        bind:
          propagation: rslave
      - type: bind
        source: /var/run
        target: /var/run
        read_only: true
        bind:
          propagation: rslave
      - type: bind
        source: /sys
        target: /sys
        read_only: true
        bind:
          propagation: rslave
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        read_only: true
        bind:
          propagation: rslave
    privileged: true
    devices:
      - "/dev/kmsg:/dev/kmsg"
    restart: unless-stopped
